services:
  - type: worker
    name: VarkiloTrackBot
    env: python
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "python bot.py"
    plan: starter
    pythonVersion: 3.10.13
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
